export const GET_TABLES = "GET_TABLES";
export const GET_USER = "GET_USER";
export const GET_RESULTS = "GET_RESULTS";
export const GET_TICKETS = "GET_TICKETS";
export const GET_TOTAL_COMPARISONS = "GET_TOTAL_COMPARISONS";
export const GET_COMPARISON_COUNT = "GET_COMPARISON_COUNT";
export const GET_SELECTED_TABLES = "GET_SELECTED_TABLES";
export const GET_PREVIOUS_TICKETS = "GET_PREVIOUS_TICKETS";